### ISSUE TITLE
Signing into Perplexity

### ISSUE THREAD

**Issue by TheWood1978** [inulute/ai-gate#2]
Hi

How can we use the login code emailed to us when logging into Perplexity.

It opens in a browser and not recognized by the app.

Regards

**Comment by inulute** [comment]
Hey, sorry for the delay in responding. I'll be pushing an update with the fix soon.

**Comment by inulute** [comment]
Hello, extremely sorry for the delay, please update to v3.0.0.

Thankyou!!!
