### ISSUE TITLE
login with cookies

### ISSUE THREAD

**Issue by kittenvr** [inulute/ai-gate#4]
allow you to login to all services using cookies

**Comment by dm-090504** [comment]
simular to how [seal](https://github.com/JunkFood02/Seal) does it?

**Comment by kittenvr** [comment]
Yeah

**Comment by inulute** [comment]
We'll look into this! Thank you!

**Comment by inulute** [comment]
> allow you to login to all services using cookies

Hello, we looked into this, but it isn’t feasible in this context due to technical constraints and policy restrictions. Allowing each service to manage its own authentication while maintaining session persistence offers a secure and user-friendly experience. Thankyou!
